# Generated by Django 4.0.4 on 2022-11-24 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.CharField(max_length=10, verbose_name='unique ID of the course')),
                ('class_name', models.CharField(max_length=75, verbose_name='name of course')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colleges.college')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='this is the name of the department', max_length=50, unique=True, verbose_name='Department Name')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('classes', models.ManyToManyField(to='colleges.collegeclasses')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colleges.college')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='colleges.department')),
            ],
        ),
        migrations.AddField(
            model_name='collegeclasses',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='colleges.department'),
        ),
        migrations.AddField(
            model_name='college',
            name='departments',
            field=models.ManyToManyField(help_text='Possible Departments in College', to='colleges.department'),
        ),
        migrations.AddConstraint(
            model_name='professor',
            constraint=models.UniqueConstraint(fields=('college', 'department', 'first_name', 'last_name'), name='class_subject_alt_key'),
        ),
        migrations.AddConstraint(
            model_name='collegeclasses',
            constraint=models.UniqueConstraint(fields=('college', 'department', 'class_name', 'class_id'), name='college_classes_alt_key'),
        ),
    ]
