# Generated by Django 4.0.4 on 2023-02-12 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=15, verbose_name='unique ID of the course')),
                ('course_name', models.CharField(max_length=75, verbose_name='name of course')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colleges.college')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='this is the name of the department', max_length=50, unique=True,
                                          verbose_name='Department Name')),
            ],
        ),
        migrations.CreateModel(
            name='SemesterYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('grading_difficulty', models.PositiveSmallIntegerField(default=1)),
                ('take_again', models.PositiveSmallIntegerField(default=1)),
                ('teaching_quality', models.PositiveSmallIntegerField(default=1)),
                ('personality', models.PositiveSmallIntegerField(default=1)),
                ('slug', models.SlugField(blank=True, max_length=40)),
                ('classes', models.ManyToManyField(to='colleges.collegecourse')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colleges.college')),
                (
                'department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='colleges.department')),
            ],
        ),
        migrations.AddField(
            model_name='collegecourse',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='colleges.department'),
        ),
        migrations.AddField(
            model_name='college',
            name='departments',
            field=models.ManyToManyField(help_text='Possible Departments in College', to='colleges.department'),
        ),
        migrations.AddConstraint(
            model_name='professor',
            constraint=models.UniqueConstraint(fields=('college', 'department', 'first_name', 'last_name'),
                                               name='class_subject_alt_key'),
        ),
        migrations.AddConstraint(
            model_name='professor',
            constraint=models.CheckConstraint(
                check=models.Q(('grading_difficulty__isnull', False), ('grading_difficulty__range', (1, 5)),
                               ('personality__isnull', False), ('personality__range', (1, 5)),
                               ('take_again__isnull', False), ('take_again__range', (1, 5)),
                               ('teaching_quality__isnull', False), ('teaching_quality__range', (1, 5))),
                name='check_professor'),
        ),
        migrations.AddConstraint(
            model_name='collegecourse',
            constraint=models.UniqueConstraint(fields=('college', 'department', 'course_name', 'course_id'),
                                               name='college_classes_alt_key'),
        ),
    ]
