# Generated by Django 4.0.4 on 2023-02-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('colleges', '0002_collegecourse_department_semesteryear_professor_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='collegecourse',
            name='college_classes_alt_key',
        ),
        migrations.RenameField(
            model_name='professor',
            old_name='classes',
            new_name='courses',
        ),
        migrations.AddField(
            model_name='collegecourse',
            name='slug',
            field=models.SlugField(blank=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='college',
            name='departments',
            field=models.ManyToManyField(blank=True, help_text='Possible Departments in College',
                                         to='colleges.department'),
        ),
        migrations.AlterField(
            model_name='collegecourse',
            name='course_name',
            field=models.CharField(max_length=90, verbose_name='name of course'),
        ),
        migrations.AddConstraint(
            model_name='collegecourse',
            constraint=models.UniqueConstraint(fields=('college', 'department', 'course_name', 'course_id'),
                                               name='college_course_alt_key'),
        ),
    ]
