# Generated by Django 4.0.4 on 2022-12-07 21:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('colleges', '0003_semesteryear'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CollegeClasses',
            new_name='CollegeClass',
        ),
        migrations.AddField(
            model_name='professor',
            name='slug',
            field=models.SlugField(blank=True, max_length=40),
        ),
        migrations.AddConstraint(
            model_name='college',
            constraint=models.UniqueConstraint(fields=('email_domain',), name='email_alt_key'),
        ),
    ]
