# Generated by Django 4.0.4 on 2022-08-19 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0003_department_collegeclasses_college_departments_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('classes', models.ManyToManyField(to='colleges.collegeclasses')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colleges.college')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='colleges.department')),
            ],
        ),
        migrations.AddConstraint(
            model_name='professor',
            constraint=models.UniqueConstraint(fields=('college', 'department', 'first_name', 'last_name'), name='class_subject_alt_key'),
        ),
    ]
