# Generated by Django 4.0.4 on 2022-12-07 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0003_semesteryear'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='grading_difficulty',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='professor',
            name='personality',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='professor',
            name='take_again',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='professor',
            name='teaching_quality',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name='professor',
            constraint=models.CheckConstraint(check=models.Q(('grading_difficulty__isnull', False), ('grading_difficulty__range', (1, 5)), ('personality__isnull', False), ('personality__range', (1, 5)), ('take_again__isnull', False), ('take_again__range', (1, 5)), ('teaching_quality__isnull', False), ('teaching_quality__range', (1, 5))), name='check_professor'),
        ),
    ]
