# Generated by Django 4.0.4 on 2023-02-18 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('colleges', '0005_requestcourse_requestprofessor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestprofessor',
            name='courses',
        ),
        migrations.AddField(
            model_name='requestprofessor',
            name='courses',
            field=models.TextField(blank=True, null=True),
        ),
    ]
