# Generated by Django 4.0.4 on 2023-02-18 19:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('colleges', '0006_remove_requestprofessor_courses_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='professor',
            name='check_professor',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='grading_difficulty',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='personality',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='take_again',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='teaching_quality',
        ),
        migrations.AlterField(
            model_name='requestprofessor',
            name='courses',
            field=models.TextField(blank=True, help_text='Please use the course IDs, comma-separated.', null=True),
        ),
    ]
