# Generated by Django 4.0.4 on 2022-12-03 23:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('colleges', '0003_collegeclasses_take_again_collegeclasses_test_heavy_and_more'),
        ('college_reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessorReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('comment', models.CharField(max_length=160)),
                ('grading_difficulty', models.PositiveSmallIntegerField()),
                ('take_again', models.PositiveSmallIntegerField()),
                ('teaching_quality', models.PositiveSmallIntegerField()),
                ('personality', models.PositiveSmallIntegerField()),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='colleges.professor')),
                ('term', models.ManyToManyField(to='college_reviews.term')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='professorreview',
            constraint=models.CheckConstraint(check=models.Q(('grading_difficulty__isnull', False), ('grading_difficulty__range', (1, 5)), ('personality__range', (1, 5)), ('take_again__isnull', False), ('take_again__range', (1, 5)), ('teaching_quality__isnull', False), ('teaching_quality__range', (1, 5))), name='check_professor_review'),
        ),
    ]
