# Generated by Django 4.0.4 on 2023-02-12 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0002_collegecourse_department_semesteryear_professor_and_more'),
        ('users', '0002_groups_and_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='courses',
            field=models.ManyToManyField(to='colleges.collegecourse'),
        ),
        migrations.AddField(
            model_name='user',
            name='major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='colleges.department'),
        ),
    ]
