# Generated by Django 4.0.4 on 2023-02-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('colleges', '0003_remove_collegecourse_college_classes_alt_key_and_more'),
        ('users', '0003_user_courses_user_major'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='courses',
            field=models.ManyToManyField(blank=True, to='colleges.collegecourse'),
        ),
    ]
